name: CI/CD Pipeline

# Define when the workflow should run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (Optional)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and tag the Docker image
      - name: Build Docker image
        run: docker build -t library-system:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker tag library-system:latest ${{ secrets.DOCKER_USERNAME }}/library-system:latest && \
             docker push ${{ secrets.DOCKER_USERNAME }}/library-system:latest